id: AC727C4A8
base_file: f9E7D.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:58:05.837165
  last_modified_at: 2022-05-30 20:58:05.837174
